# Inleiding

In een eerdere publicatie van Kennisplatform Integratie &
Samenleving kwam een zorgelijk beeld naar voren van de
leefomstandigheden van kinderen met een Antilliaanse- of
Arubaanse achtergrond in Nederland (Tierolf, Steketee, Gilsing
& Bellaart, 2017). Het was opvallend dat kinderen met een Antilliaanse achtergrond, vergeleken met jeugd van andere herkomst, het hoogst scoren op de risico’s op armoede, eenoudergezinnen, jeugdwerkloosheid en gebruik jeugdhulp. Er zijn grote verschillen in de leefomstandigheden waarin kinderen zonder en met een migratieachtergrond opgroeien. Het maakt uit in welke wijk je opgroeit.

Jeugdigen met een Antilliaanse achtergrond wonen vaker in de
slechtere, kansarme wijken en voelen zich daar minder veilig.
Ondanks de gemiddelde slechtere leefomstandigheden doet een
deel van de Antilliaanse jongeren het wel goed in het onderwijs
en op de arbeidsmarkt. Het opleidingsniveau van deze jongeren
stijgt gestaag, maar al met al is het beeld dat de leefomstandigheden van een relatief groot deel van de inwoners met een Antilliaanse achtergrond niet zo rooskleurig zijn.

Actieve organisaties voor en door Antilliaanse Nederlanders in
Den Haag, HAAB en OCAN hebben Kennisplatform Integratie
& Samenleving verzocht om de situatie in Den Haag in kaart te
brengen. Dit zou kunnen dienen als een voorbeeld voor andere
gemeenten. Deze organisaties willen graag meer inzicht krijgen
in de specifieke problemen en de kansen om daar nieuwe
projecten voor te ontwikkelen. Zij willen als zelforganisaties zich versterken en samen met anderen de maatschappelijke situatie van veel Antilliaanse Nederlanders verbeteren.
Voorliggend factsheet hoopt aan de vraag van HAAB en OCAN te
voldoen. Op een groot aantal thema’s zijn kerncijfers verzameld.
Bij ieder beeld wordt uitleg gegeven en een korte verklaring van de mate waarin de cijfers van bepaalde groepen verschillen van elkaar en van het gemiddelde in Nederland.